language: python
python: 3.8
env:
  global:
    - PYTHON_VERSION: 3.8
if: (type = push AND branch = master)
stages:
  - Build
  - Lint
  - Unit Test
install:
  - python -m pip install --upgrade pip
  - 'pip install -e .[dev]'
_shared_script: null
script:
  - coverage run --branch -m xmlrunner -o junit discover
  - coverage xml --include="./arm/avhclient/**"
_ubuntu_latest: null
os: linux
dist: focal
jobs:
  include:
    - stage: Build
      name: Build Distribution
      install:
        - python -m pip install --upgrade pip
        - pip install -U setuptools twine wheel
      script:
        - python setup.py sdist bdist_wheel
        - twine check dist/*
    - stage: Lint
      name: Run PyLint checks
      install:
        - python -m pip install --upgrade pip
        - 'pip install -e .[dev]'
      script:
        - 'echo "::add-matcher::.github/pylint.json"'
        - pylint --exit-zero --rcfile=./pylintrc arm/avhclient tests
    - stage: Unit Tests
      name: Unit Tests - Ubuntu - Python3.8
      env:
        - AWS_DEFAULT_REGION="eu-west-1"
      python: 3.8
    - stage: Unit Tests
      name: Unit Tests - Ubuntu - Python3.9
      env:
        - AWS_DEFAULT_REGION="eu-west-1"
      python: 3.9
    - stage: Unit Tests
      name: Unit Tests - Ubuntu - Python3.10
      env:
        - AWS_DEFAULT_REGION="eu-west-1"
      os: osx
      osx_image: xcode13.3
      language: shell
      before_install: python3 --version; pip3 --version; sw_vers
      install:
        - python3 -m pip install --upgrade pip
        - pip3 install codecov
        - 'pip install -e .[dev] --user'
        
   ## Refactored by me for more traditional .travis.yml feel, although I stil have anchoring methods.
